concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
session_timeout = 1800

[[runners]]
name = "Docker Runner"
url = "https://gitlab.com/"
id = 31097074
token = "glrt-*****"
token_obtained_at = 2023-12-31T12:48:25Z
token_expires_at = 0001-01-01T00:00:00Z
executor = "docker"
[runners.feature_flags]
FF_NETWORK_PER_BUILD = true
[runners.cache]
MaxUploadedArchiveSize = 0
[runners.docker]
tls_verify = false
image = "docker:24.0.5"
privileged = true
disable_entrypoint_overwrite = false
oom_kill_disable = false
disable_cache = false
volumes = ["/cache"]
shm_size = 0
network_mtu = 0