version: '3.7'

services:
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    restart: always
    container_name: gitlab-runner
    volumes:
      - ./config/:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock